--- #YAML:1.0
 name: Lingua-EN-Nums2Words
 abstract: generate English verbiage from numerical values
 version: 1.14
 author:
   - Lester H. Hightower, Jr. <hightowe@cpan.org>
 license: perl
 distribution_type: module
 requires:
 recommends:
 build_requires:
 urls:
   license: http://dev.perl.org/licenses/
 meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
 generated_by: Module::Build version 0.20
